services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      NODE_ENV: development
      DATABASE_URL: mysql://root:admin@mysql:3306/proj


  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: proj
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

volumes:
  db_data: